### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by karl2k** [ignasr/dok#1]
Can you provide an updated svn path?  Subversion has recently taken it down

**Comment by ignasr** [comment]
Hi, which svn path do you have in mind?

**Comment by karl2k** [comment]
I wouldn't be able to rehost it, but the svn path for sysloggen is no longer reachable

**Comment by ignasr** [comment]
I know as much as you, as I am not the creator of sysloggen, nor the owner of that repo. You could try http://www.logzilla.net/download.html, maybe that script is somewhere there in the source code.
